project:
  type: website

website:
  title: "Weather Dashboard Project: WeatherVista (天气景观 - Tiānqì jǐngguān)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

render: 
    - "*.qmd"
    - "!*.ipynb"


